-- Schema-integrity hardening (applied to project pjuwipjyxzxlmhebzdct on 2026-07-03).

-- 1. Enforce uniqueness of measurements at the schema level (uniqueness previously held only in data).
ALTER TABLE public.lab_results ADD CONSTRAINT lab_results_marker_date_key UNIQUE (marker, test_date);
-- The unique index above shares the leading columns of idx_lab_results_marker_date, which becomes redundant.
DROP INDEX IF EXISTS public.idx_lab_results_marker_date;
ALTER TABLE public.food_panels ADD CONSTRAINT food_panels_panel_food_key UNIQUE (panel, food);
ALTER TABLE public.food_guide  ADD CONSTRAINT food_guide_food_de_key     UNIQUE (food_de);

-- 2. Make food_reactions.id consistent with every other table (GENERATED IDENTITY, not a bare sequence default).
ALTER TABLE public.food_reactions ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS public.food_reactions_id_seq;
ALTER TABLE public.food_reactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2);
